<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE book [
		<!ELEMENT book (book_name,(chapter+))>
		<!ELEMENT book_name (#PCDATA)>
		<!ELEMENT chapter (chapter_id|chapter_name|paragraph)*>
		<!ELEMENT chapter_id (#PCDATA)>
		<!ELEMENT chapter_name (#PCDATA)>
		<!ELEMENT paragraph (p_id|p_name|section|exercise|exercises_block|questions_block|pictures|exercises|questions|additional_exercises|additional_questions|additional_exercise|s_name|building_tasks|question|hard_exercise|name|picture)*>
		<!ELEMENT p_id (#PCDATA)>
		<!ELEMENT p_name (#PCDATA)>
		<!ELEMENT section (s_id|s_name|text|definition|pictures|section_text|theorem|building_task|exercises_block|questions_block|additional_exercises_block|example|picture|exercise)*>
		<!ELEMENT s_id (#PCDATA)>
		<!ELEMENT s_name (#PCDATA)>
		<!ELEMENT text (pictures|definition|theorem|msqrt)*>
		<!ELEMENT definition (#PCDATA)>
		<!ATTLIST definition
				name CDATA #REQUIRED>
		<!ELEMENT pictures (picture)*>
		<!ELEMENT picture (img|text|name)*>
		<!ELEMENT img (#PCDATA)>
		<!ATTLIST img
				src CDATA #REQUIRED>
		<!ELEMENT exercise (e_id|text|pictures|id|exercise_text|solution|exercise)*>
		<!ATTLIST exercise
				id CDATA #IMPLIED>
		<!ELEMENT e_id (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT exercises_block (exercise|pictures)*>
		<!ATTLIST exercises_block
				header CDATA #IMPLIED
				name CDATA #IMPLIED>
		<!ELEMENT section_text (text|pictures|theorem|axiom|axiom_id|definition|consequence|picture|comment|example)*>
		<!ELEMENT questions_block (question)*>
		<!ATTLIST questions_block
				header CDATA #IMPLIED
				name CDATA #IMPLIED>
		<!ELEMENT question (q_id|text|id|pictures|questions_text|question_text)*>
		<!ELEMENT q_id (#PCDATA)>
		<!ELEMENT exercises (exercise)*>
		<!ELEMENT id (#PCDATA)>
		<!ELEMENT questions (question|id|text|q_id|question_id|questions_text|section_text)*>
		<!ATTLIST questions
				id CDATA #IMPLIED>
		<!ELEMENT additional_exercises (additional_exercise|add_ex_id|text)*>
		<!ELEMENT additional_exercise (id|text|add_ex_id|additional_exercise_text)*>
		<!ATTLIST additional_exercise
				id CDATA #IMPLIED>
		<!ELEMENT theorem (t_text|proof|comment|text|consequence|pictures)*>
		<!ATTLIST theorem
				name CDATA #IMPLIED>
		<!ELEMENT t_text (#PCDATA)>
		<!ELEMENT proof (pictures|text|proof_text|picture)*>
		<!ATTLIST proof
				header CDATA #IMPLIED>
		<!ELEMENT building_task (building_task_text|decisions|notes)*>
		<!ATTLIST building_task
				header CDATA #REQUIRED>
		<!ELEMENT building_task_text (#PCDATA)>
		<!ATTLIST building_task_text
				header CDATA #REQUIRED>
		<!ELEMENT decisions (#PCDATA)>
		<!ATTLIST decisions
				header CDATA #IMPLIED>
		<!ELEMENT notes (#PCDATA)>
		<!ATTLIST notes
				header CDATA #REQUIRED>
		<!ELEMENT exercise_text (#PCDATA)>
		<!ELEMENT solution (pictures)*>
		<!ATTLIST solution
				header CDATA #IMPLIED>
		<!ELEMENT questions_text (#PCDATA)>
		<!ELEMENT additional_exercises_block (additional_exercise)*>
		<!ATTLIST additional_exercises_block
				header CDATA #REQUIRED>
		<!ELEMENT add_ex_id (#PCDATA)>
		<!ELEMENT additional_exercise_text (#PCDATA)>
		<!ELEMENT axiom (text)*>
		<!ELEMENT axiom_id (text)*>
		<!ELEMENT comment (text|proof|definition|id)*>
		<!ELEMENT consequence (text|proof|consequence_id|consequence_text|pictures)*>
		<!ATTLIST consequence
				parent CDATA #IMPLIED>
		<!ELEMENT additional_questions (add_q_id|text)*>
		<!ELEMENT add_q_id (#PCDATA)>
		<!ELEMENT consequence_id (#PCDATA)>
		<!ELEMENT proof_text (text|ID)*>
		<!ELEMENT example (example_id|text|solution|e_id|pictures)*>
		<!ELEMENT example_id (id)*>
		<!ELEMENT building_tasks (b_id|text|decisions|pictures|analysis|construction|evidence|research|building_tasks_id|id|building_tasks_text)*>
		<!ELEMENT b_id (#PCDATA)>
		<!ELEMENT hard_exercise (name|exercise|text|building_tasks|id|clause)*>
		<!ELEMENT analysis (#PCDATA)>
		<!ELEMENT construction (#PCDATA)>
		<!ELEMENT evidence (#PCDATA)>
		<!ELEMENT research (#PCDATA)>
		<!ELEMENT question_id (#PCDATA)>
		<!ELEMENT consequence_text (#PCDATA)>
		<!ELEMENT msqrt (#PCDATA)>
		<!ELEMENT building_tasks_id (#PCDATA)>
		<!ELEMENT ID (#PCDATA)>
		<!ELEMENT building_tasks_text (#PCDATA)>
		<!ELEMENT question_text (#PCDATA)>
		<!ELEMENT clause (#PCDATA)>
		]>
<book>
	<book_name>Атанасян Л.С. и др. Геометрия. 7-9 классы: учебник для общеобразовательных учреждений. 2010 год издания</book_name>
	<chapter>
		<chapter_id>1</chapter_id>
		<chapter_name>Начальные геометрические сведения</chapter_name>
		<paragraph>
			<p_id>1</p_id>
			<p_name>Прямая и отрезок</p_name>
			<section>
				<s_id>1</s_id>
				<s_name>Точки, прямые, отрезки</s_name>
				<text>Вспомним, что нам известно о точках и прямых. Мы знаем, что для изображения прямых на чертеже пользуются линейкой (рис.4), но при этом можно изобразить лишь часть прямой, а всю прямую мы представляем себе простирающейся бесконечно в обе стороны. Обычно прямые обозначают малыми латинскими буквами, а точки - большими латинскими буквами. На рисунке 5 изображены прямая a и точки A, B, C и D. Точки A и B лежат на прямой a, а точки C и D не лежат на этой прямой. Можно сказать, что прямая a проходит через точки A и B, но не проходит через точки C и D. Отметим, что через точки A и B нельзя провести другую прямую, не совпадающую с прямой a. Вообще, через любые две точки можно провести прямую, и притом только одну. Рассмотрим теперь две прямые. Если они имеют общую точку, то говорят, что эти прямые пересекаются. На рисунке 6 прямые a и b пересекаются в точке O, а прямые p и q не пересекаются. Две прямые не могут иметь двух и более общих точек. В самом деле, если бы две прямые имели две общие точки, то каждая из прямых проходила бы через эти точки. Но через две точки проходит только одна прямая. Таким образом, можно сделать вывод: две прямые либо имеют только одну общую точку, либо не имеют общих точек. Прямую, на которой отмечены две точки, например A и B, иногда обозначают двумя буквами: AB или BA. Для краткости вместо слов «точка A лежит на прямой a» используют запись A принадлежит a, а вместо слов «точка B не лежит на прямой a» - запись B не принадлежит a.</text>
				<definition name = "Отрезок">На рисунке 7, а выделена часть прямой, ограниченная двумя точками. Такая часть прямой называется отрезком.</definition>
				<definition name = "Концы отрезка">Точки, ограничивающие отрезок, называются его концами. На рисунке 7, б изображен отрезок с концами A и B.</definition>
				<text>Такой отрезок обозначается AB или BA. Отрезок AB содержит точки A и B и все точки прямой AB, лежащие между A и B.</text>
				<pictures>
					<picture>
						<img src = "4.png"/>
						<text>Рис.4</text>
					</picture>
					<picture>
						<img src = "5.png"/>
						<text>Рис.5</text>
					</picture>
					<picture>
						<img src = "6.png"/>
						<text>Рис.6</text>
					</picture>
					<picture>
						<img src = "7а.png"/>
						<text>Рис.7а</text>
					</picture>
					<picture>
						<img src = "7б.png"/>
						<text>Рис.7б</text>
					</picture>
				</pictures>
			</section>
			<section>
				<s_id>2</s_id>
				<s_name>Провешивание прямой на местности</s_name>
				<text>Решим такую задачу: с помощью данной линейки построить отрезок более длинный, чем сама линейка. С этой целью приложим к листу бумаги линейку, отметим точки A и B и какую-нибудь точку C, лежащую между A и B (рис.8, а). Затем передвинем линейку вправо так, чтобы ее левый конец оказался около точки C, и отметим точку D около правого конца линейки (рис.8, б). Точки A, B, C и D лежат на одной прямой. Если мы проведем теперь отрезок AB, а затем отрезок BD, то получим отрезок AD, более длинный, чем линейка. Аналогичный прием используется для «проведения» длинных отрезков прямых на местности. Этот прием заключается в следующем. Сначала отмечают какие-нибудь точки A и B. Для этой цели используют две вехи - шесты длиной около 2 м, заостренные на одном конце для того, чтобы их можно было воткнуть в землю. Третью веху ставят так, чтобы вехи, стоящие в точках A и B, закрывали ее от наблюдателя, находящегося в точке A (точка C на рисунке 9). Следующую веху ставят так, чтобы ее закрывали вехи, стоящие в точках B и C, и т.д. Описанный прием называется провешиванием прямой. Он широко используется на практике, например при рубке лесных просек, при прокладывании трассы шоссейной или железной дороги, линий высоковольтных передач и т. д.</text>
				<pictures>
					<picture>
						<img src = "8а.png"/>
						<text>Рис.8а</text>
					</picture>
					<picture>
						<img src = "8б.png"/>
						<text>Рис.8б</text>
					</picture>
					<picture>
						<img src = "9.png"/>
						<text>Рис.9</text>
					</picture>
					<picture>
						<img src = "10.png"/>
						<text>Рис.10</text>
					</picture>
				</pictures>
			</section>
			<exercise>
				<e_id>1</e_id>
				<text>Проведите прямую, обозначьте ее буквой а и отметьте точки А и В, лежащие на этой прямой, и точки Р, Q и R, не лежащие на ней. Опишите взаимное расположение точек А, В, Р, Q, R и прямой а, используя символы принадлежности.</text>
			</exercise>
			<exercise>
				<e_id>2</e_id>
				<text>Отметьте три точки А, В и С, не лежащие на одной прямой, и проведите прямые AB, ВС и СА.</text>
			</exercise>
			<exercise>
				<e_id>3</e_id>
				<text>Проведите три прямые так, чтобы каждые две из них пересекались. Обозначьте все точки пересечения этих прямых. Сколько получилось точек? Рассмотрите все возможные случаи.</text>
			</exercise>
			<exercise>
				<e_id>4</e_id>
				<text>Отметьте точки А, В, С, D так, чтобы точки А, В, С лежали на одной прямой, а точка D не лежала на ней. Через каждые две точки проведите прямую. Сколько получилось прямых?</text>
			</exercise>
			<exercise>
				<e_id>5</e_id>
				<text>Проведите прямую а и отметьте на ней точки А и В. Отметьте: а) точки М и N, лежащие на отрезке AB; б) точки Р и Q, лежащие на прямой а, но не лежащие на отрезке AB; в) точки R и S, не лежащие на прямой а.</text>
			</exercise>
			<exercise>
				<e_id>6</e_id>
				<text>Проведите прямую и отметьте на ней три точки. Сколько отрезков получилось на прямой?</text>
			</exercise>
		</paragraph>
		<paragraph>
			<p_id>2</p_id>
			<p_name>Луч и угол</p_name>
			<section>
				<s_id>3</s_id>
				<s_name>Луч</s_name>
				<text>Проведем прямую а и отметим на ней точку O (рис.11). Эта точка разделяет прямую на две части, каждая из которых называется лучом, исходящим из точки O (на рисунке 11 один из лучей выделен цветной линией). Точка O называется началом каждого из лучей. Обычно луч обозначают либо малой латинской буквой (например, луч h на рисунке 12, а), либо двумя большими латинскими буквами, первая из которых обозначает начало луча, а вторая - какую-нибудь точку на луче (например, луч OA на рисунке 12, 6).</text>
				<pictures>
					<picture>
						<img src = "11.png"/>
						<name>Рис.11</name>
					</picture>
					<picture>
						<img src = "12а.png"/>
						<text>Рис.12а</text>
					</picture>
					<picture>
						<img src = "12б.png"/>
						<text>Рис.12б</text>
					</picture>
				</pictures>
			</section>
			<section>
				<s_id>4</s_id>
				<s_name>Угол</s_name>
				<text>Напомним, что угол - это геометрическая фигура, которая состоит из точки и двух лучей, исходящих из этой точки. Лучи называются сторонами угла, а их общее начало - вершиной угла. На рисунке 13 изображен угол с вершиной O и сторонами h и k. На сторонах отмечены точки A и B. Этот угол обозначают так: Lhk , или LAOB, или LO. Угол называется развернутым, если обе его стороны лежат на одной прямой. Можно сказать, что каждая сторона развернутого угла является продолжением другой стороны. На рисунке 14 изображен развернутый угол с вершиной C и сторонами р и q. Любой угол разделяет плоскость на две части. Если угол неразвернутый, то одна из частей называется внутренней, а другая - внешней областью этого угла (рис.15, а). На рисунке 15, б изображен неразвернутый угол. Точки A, B, C лежат внутри этого угла (т. е. во внутренней области угла), точки D и E - на сторонах угла, а точки P и Q - вне угла (т. е. во внешней области угла). Если угол развернутый, то любую из двух частей, на которые он разделяет плоскость, можно считать внутренней областью угла. Фигуру, состоящую из угла и его внутренней области, также называют углом. Если луч исходит из вершины не развернутого угла и проходит внутри угла, то он делит этот угол на два угла. На рисунке 16, а луч OC делит угол AOB на два угла: AOC и COB. Если угол AOB развернутый, то любой луч OC, не совпадающий с лучами OA и OB, делит этот угол на два угла: AOC и COB (рис.16, б)</text>
				<pictures>
					<picture>
						<img src = "13.png"/>
						<text>Рис.13</text>
					</picture>
					<picture>
						<img src = "14.png"/>
						<text>Рис.14</text>
					</picture>
					<picture>
						<img src = "15а.png"/>
						<text>Рис.15а</text>
					</picture>
					<picture>
						<img src = "15б.png"/>
						<text>Рис.15б</text>
					</picture>
					<picture>
						<img src = "16а.png"/>
						<text>Рис.16а</text>
					</picture>
					<picture>
						<img src = "16б.png"/>
						<text>Рис.16б</text>
					</picture>
				</pictures>
			</section>
			<exercises_block name='Практические задания и вопросы'>
				<exercise>
					<e_id>8</e_id>
					<text>Проведите прямую, отметьте на ней точки A и B и на отрезке AB отметьте точку C. а) Среди лучей AB, BC, CA, AC и BA назовите совпадающие лучи; б) назовите луч, который является продолжением луча CA.</text>
				</exercise>
				<exercise>
					<e_id>9</e_id>
					<text>Начертите три неразвернутых угла и обозначьте их так: LAOB, Lhk , LM .</text>
				</exercise>
				<exercise>
					<e_id>10</e_id>
					<text>Начертите два развернутых угла и обозначьте их буквами.</text>
				</exercise>
				<exercise>
					<e_id>11</e_id>
					<text>Начертите три луча h, k и l с общим началом. Назовите все углы, образованные данными лучами.</text>
				</exercise>
				<exercise>
					<e_id>12</e_id>
					<text>Начертите неразвернутый угол hk . Отметьте две точки внутри этого угла, две точки вне этого угла и две точки на сторонах угла.</text>
				</exercise>
				<exercise>
					<e_id>13</e_id>
					<text>Начертите неразвернутый угол . Отметьте точки A, B, M и N так, чтобы все точки отрезка AB лежали внутри угла, а все точки отрезка MN лежали вне угла.</text>
				</exercise>
				<exercise>
					<e_id>14</e_id>
					<text>Начертите неразвернутый угол AOB и проведите: а) луч OC, который делит угол AOB на два угла; б) луч OD, который не делит угол AOC на два угла.</text>
				</exercise>
				<exercise>
					<e_id>15</e_id>
					<text>Сколько неразвернутых углов образуется при пересечении двух прямых?</text>
				</exercise>
				<exercise>
					<e_id>16</e_id>
					<text>Какие из точек, изображенных на рисунке 17, лежат внутри угла hk, а какие - вне этого угла?</text>
					<pictures>
						<picture>
							<img src = "17.png"/>
							<text>Рис.17</text>
						</picture>
					</pictures>
				</exercise>
				<exercise>
					<e_id>17</e_id>
					<text>Какие из лучей, изображенных на рисунке 18, делят угол AOB на два угла?.</text>
					<pictures>
						<picture>
							<img src = "18.png"/>
							<name>Рис.18</name>
						</picture>
					</pictures>
				</exercise>
			</exercises_block>
		</paragraph>
		<paragraph>
			<p_id>3</p_id>
			<p_name>Сравнение отрезков и углов</p_name>
			<section>
				<s_id>5</s_id>
				<s_name>Равенство геометрических фигур</s_name>
				<section_text>
					<text>Среди окружающих нас предметов встречаются такие, которые имеют одинаковую форму и одинаковые размеры. Такими предметами являются, например, два одинаковых листа бумаги, две одинаковые книги, два одинаковых автомобиля. В геометрии две фигуры, имеющие одинаковую форму и одинаковые размеры, называют равными. На рисунке 19 изображены фигуры Ф1 и Ф2. Чтобы установить, равны они или нет, поступим так. Скопируем фигуру Ф1 на кальку. Передвигая кальку и накладывая ее на фигуру Ф2 той или другой стороной, попытаемся совместить копию фигуры Ф1 с фигурой Ф2. Если они совместятся, то фигура Ф1 равна фигуре Ф2. Мы можем представить себе, что на фигуру Ф2 накладывается не копия фигуры Ф1, равная этой фигуре, а сама фигура Ф1. Поэтому в дальнейшем будем говорить о наложении самой фигуры (а не копии) на другую фигуру. Итак, две геометрические фигуры называются равными, если их можно совместить наложением.</text>
					<pictures>
						<picture>
							<img src = "19.png"/>
							<text>Рис.19</text>
						</picture>
					</pictures>
				</section_text>
			</section>
			<section>
				<s_id>6</s_id>
				<s_name>Сравнение отрезков и углов</s_name>
				<section_text>
					<text>На рисунке 20,а изображены два отрезка. Чтобы установить, равны они или нет, наложим один отрезок на другой так, чтобы конец одного отрезка совместился с концом другого (рис.20,б). Если при этом два других конца также совместятся, то отрезки полностью совместятся и, значит, они равны.Если же два других конца не совместятся, то меньшим считается тот отрезок, который составляет часть другого. На рисунке 20,в отрезок AC составляет часть отрезка AB, поэтому отрезок AC меньше отрезка AB (пишут так: AC &lt; AB) Точка отрезка, делящая его пополам, т.е. на два равных отрезка, называется серединой отрезка. На рисунке 21 точка С – середина отрезка AB. На рисунке 22,a изображены неразвернутые углы 1 и 2. Чтобы установить, равны они или нет, наложим один угол на другой так, чтобы сторона одного угла совместилась со стороной другого, а две другие оказались по одну сторону от совместившихся сторон (рис.22,б). Если две другие стороны также совместятся, то углы полностью совместятся и, значит, они равны. Если же эти стороны не совместятся, то меньшим считается тот угол, который составляет часть другого. На рисунке 22, б угол 1 составляет часть угла 2, поэтому &#8735;1 &lt; &#8735;2. Неразвернутый угол составляет часть развернутого угла (рис.23), поэтому развернутый угол больше неразвернутого угла. Любые два развернутых угла, очевидно, равны. Луч, исходящий из вершины угла и делящий его на два равных угла, называется биссектрисой угла. На рисунке 24 луч l – биссектриса угла hk.</text>
					<pictures>
						<picture>
							<img src = "20а.png"/>
							<text>Рис.20а</text>
						</picture>
						<picture>
							<img src = "20б.png"/>
							<text>Рис.20б</text>
						</picture>
						<picture>
							<img src = "20в.png"/>
							<text>Рис.20в</text>
						</picture>
						<picture>
							<img src = "21.png"/>
							<text>Рис.21</text>
						</picture>
						<picture>
							<img src = "22а.png"/>
							<text>Рис.22а</text>
						</picture>
						<picture>
							<img src = "22б.png"/>
							<text>Рис.22б</text>
						</picture>
						<picture>
							<img src = "23.png"/>
							<text>Рис.23</text>
						</picture>
						<picture>
							<img src = "24.png"/>
							<text>Рис.24</text>
						</picture>
					</pictures>
				</section_text>
			</section>
			<exercise>
				<e_id>18</e_id>
				<text>На луче с началом O отмечены точки A, B и C так, что точка В лежит между точками О и А, а точка А – между точками О и С. Сравните отрезки ОВ и ОА, ОС и ОА, ОВ и ОС.</text>
			</exercise>
			<exercise>
				<e_id>19</e_id>
				<text>Точка О является серединой отрезка AB. Можно ли совместить наложением отрезки: а) ОА и ОВ; б)ОА и AB?</text>
			</exercise>
			<exercise>
				<e_id>20</e_id>
				<text>На рисунке 25 отрезки AB, ВС, CD, и DE равны. Укажите: а) середины отрезков AC, AE, и CE; б) отрезок, серединой которого является точка D; в) отрезки, серединой которых является точка С.</text>
				<pictures>
					<picture>
						<img src = "25.png"/>
						<text>Рис.25</text>
					</picture>
				</pictures>
			</exercise>
			<exercise>
				<e_id>21</e_id>
				<text>Луч OC делит угол AOB на два угла. Сравните углы AOB и АОС.</text>
			</exercise>
			<exercise>
				<e_id>22</e_id>
				<text>Луч l – биссектриса угла hk. Можно ли наложением совместить углы: а) hl и lk; б) hl и hk?</text>
			</exercise>
			<exercise>
				<e_id>23</e_id>
				<text>На рисунке 26,обозначенные цифрами, равны. Укажите: а) биссектрису каждого из углов АОС, BOF, AOE; б) все углы, биссектрисой которых является луч ОС.</text>
				<pictures>
					<picture>
						<img src = "26.png"/>
						<text>Рис.26</text>
					</picture>
				</pictures>
			</exercise>
		</paragraph>
		<paragraph>
			<p_id>4</p_id>
			<p_name>Измерение отрезков</p_name>
			<section>
				<s_id>7</s_id>
				<s_name>Длина отрезка</s_name>
				<text>На практике часто приходится измерять отрезки, т. е. находить их длины. Измерение отрезков основано на сравнении их с некоторым отрезком, принятым за единицу измерения (его называют также масштабным отрезком). Если, например, за единицу измерения принят сантиметр, то для определения длины отрезка узнают, сколько раз в этом отрезке укладывается сантиметр. На рисунке 27 в отрезке AB сантиметр укладывается ровно два раза. Это означает, что длина отрезка AB равна 2 см. Обычно говорят кратко: «Отрезок AB равен 2 СМ» - и пишут: AB = 2 см. Может оказаться так, что отрезок, принятый за единицу измерения, не укладывается целое число раз в измеряемом отрезке - получается остаток. Тогда единицу измерения делят на равные части, обычно на 10 равных частей, и определяют, сколько раз одна такая часть укладывается в остатке. Например, на рисунке 27 в отрезке AC сантиметр укладывается 3 раза, и в остатке ровно 4 раза укладывается одна десятая часть сантиметра (миллиметр), поэтому длина отрезка AC равна 3,4 см. Возможно, однако, что и взятая часть единицы измерения (в данном случае миллиметр) не укладывается в остатке целое число раз, и получается новый остаток. Так будет, например, с отрезком AD на рисунке 27, в котором сантиметр укладывается три раза с остатком, а в остатке миллиметр укладывается восемь раз вновь с остатком. В таком случае говорят, что длина отрезка AD приближенно равна 3,8 см. Для более точного измерения этого отрезка указанную часть единицы измерения (миллиметр) можно разделить на 10 равных частей и продолжить процесс измерения. Мысленно этот процесс можно продолжать и дальше, измеряя длину отрезка со все большей точностью. На практике, однако, пользуются приближенными значениями длин отрезков. За единицу измерения можно принимать не только сантиметр, но и любой другой отрезок. Выбрав единицу измерения, можно измерить любой отрезок, т. е. выразить его длину некоторым положительным числом. Это число показывает, сколько раз единица измерения и ее части укладываются в измеряемом отрезке. Если два отрезка равны, то единица измерения и ее части укладываются в этих отрезках одинаковое число раз, т. е. равные отрезки имеют равные длины. Если же один отрезок меньше другого, то единица измерения (или ее часть) укладывается в этом отрезке меньшее число раз, чем в другом, т. е. меньший отрезок имеет меньшую длину. На рисунке 28 изображен отрезок AB. Точка С делит его на два отрезка: AC и СВ. Мы видим, что AC = 3 см, СВ = 2, 7 см, AB = 5,7 см. Таким образом, AC + СВ = AB. Ясно, что и во всех других случаях, когда точка делит отрезок на два отрезка, длина всего отрезка равна сумме длин этих двух отрезков. Если длина отрезка CD в k раз больше длины отрезка AB, то пишут CD = kAB. Длина отрезка называется также расстоянием между концами этого отрезка.</text>
				<pictures>
					<picture>
						<img src = "27.png"/>
						<text>Рис.27</text>
					</picture>
					<picture>
						<img src = "28.png"/>
						<text>Рис.28</text>
					</picture>
				</pictures>
			</section>
			<section>
				<s_id>8</s_id>
				<s_name>Единицы измерения. Измерительные инструменты</s_name>
				<text>Для измерения отрезков и нахождения расстояний на практике используют различные единицы измерения. Стандартной международной единицей измерения отрезков выбран метр - отрезок, приближенно равный 1/40 000 000 части земного меридиана. Эталон метра в виде специального металлического бруска хранится в Международном бюро мер и весов во Франции. Копии эталона хранятся в других странах, в том числе и в России. Один метр содержит сто сантиметров. В одном сантиметре десять миллиметров. При измерении небольших расстояний, например расстояния между точками, изображенными на листе бумаги, за единицу измерения принимают сантиметр или миллиметр. Расстояние между отдельными предметами в комнате измеряют в метрах, расстояние между населенными пунктами - в километрах. Используются и другие единицы измерения, например, дециметр, морская миля (1 миля равна 1,852 км). В астрономии для измерения очень больших расстояний за единицу измерения принимают световой год, т. е. путь, который свет проходит в течение одного года. Мы назвали единицы измерения расстояний, которые используются на практике в наше время. В старину в разных странах существовали свои единицы измерения. Так, на Руси использовались аршин (О,7112 м), сажень (2,1336 м) и др. На практике для измерения расстояний пользуются различными инструментами. Например, в техническом черчении употребляется масштабная миллиметровая линейка. Для измерения диаметра трубки используют штангенциркуль (рис.29). С его помощью можно измерять расстояния с точностью до О, 1 мм. Для измерения расстояний на местности пользуются рулеткой, которая представляет собой ленту с нанесенными на ней делениями (рис.30).</text>
				<pictures>
					<picture>
						<img src = "29.png"/>
						<name>Рис.29</name>
					</picture>
					<picture>
						<img src = "30.png"/>
						<name>Рис.30</name>
					</picture>
				</pictures>
			</section>
			<exercises_block name="Практические задания и вопросы">
				<exercise>
					<e_id>24</e_id>
					<text>Измерьте ширину и длину учебника геометрии и выразите их в сантиметрах и в миллиметрах.</text>
				</exercise>
				<exercise>
					<e_id>25</e_id>
					<text>Измерив толщину учебника геометрии без обложки, найдите толщину одного листа.</text>
				</exercise>
				<exercise>
					<e_id>26</e_id>
					<text>Найдите длины всех отрезков, изображенных на рисунке 31, если за единицу измерения принят отрезок: а) KL; б) AB.</text>
					<pictures>
						<picture>
							<img src = "31.png"/>
							<name> Рис.31 </name>
						</picture>
					</pictures>
				</exercise>
				<exercise>
					<e_id>27</e_id>
					<text>Начертите отрезок AB и луч h. Пользуясь масштабной линейкой, отложите на луче h от его начала отрезки, длины которых равны 2AB, 1/2AB и 1/4AB.</text>
				</exercise>
				<exercise>
					<e_id>28</e_id>
					<text>Начертите прямую и отметьте на ней точки А и В. С помощью масштабной линейки отметьте точки С и D так, чтобы точка В была серединой отрезка AC, а точка D - серединой отрезка ВС.</text>
				</exercise>
				<exercise>
					<e_id>29</e_id>
					<text>Начертите прямую AB. С помощью масштабной линейки отметьте на этой прямой точку С, такую, что AC = 2 см. Сколько таких точек можно отметить на прямой AB?</text>
				</exercise>
			</exercises_block>
			<questions_block name="Вопросы и задачи">
				<question>
					<q_id>30</q_id>
					<text>Точка В делит отрезок AC на два отрезка. Найдите длину отрезка AC, если AB = 7,8 см, ВС = 25 мм.</text>
				</question>
				<question>
					<q_id>31</q_id>
					<text>Точка В делит отрезок AC на два отрезка. Найдите длину отрезка ВС , если: а) AB = 3,7 см, AC = 7,2 см; б) AB = 4 мм, AC = 4 см.</text>
				</question>
				<question>
					<q_id>32</q_id>
					<text>Точки А, В и С лежат на одной прямой. Известно, что AB = 12 см, ВС = 13,5 см. Какой может быть длина отрезка AC?</text>
				</question>
				<question>
					<q_id>33</q_id>
					<text>Точки В, D и М лежат на одной прямой. Известно, что BD = 7 см, MD = 16 см. Каким может быть расстояние ВМ?</text>
				</question>
				<question>
					<q_id>34</q_id>
					<text>Точка С - середина отрезка AB , равного 64 см. На луче СА отмечена точка D так, что CD = l5 см. Найдите длины отрезков BD и DA.</text>
				</question>
				<question>
					<q_id>35</q_id>
					<text>Расстояние между Москвой и С.-Петербургом равно 650 км. Город Тверь находится между Москвой и С.-Петербургом в 170 км от Москвы. Найдите расстояние между Тверью и С.-Петербургом, считая, что все три города расположены на одной прямой.</text>
				</question>
				<question>
					<q_id>36</q_id>
					<text>Лежат ли точки А, В и С на одной прямой, если AC = 5 см, AB = 3 см, ВС = 4 см?</text>
				</question>
				<question>
					<q_id>37</q_id>
					<text>Точка С - середина отрезка AB, точка 0 - середина отрезка AC. а) Найдите AC, СВ , АО и ОВ, если AB = 2 см; б) найдите AB, AC, АО и ОВ, если СВ = 3,2 м.</text>
				</question>
				<question>
					<q_id>38</q_id>
					<text>На прямой отмечены точки О, А и В так, что ОА = 12 см, ОВ = 9 см. Найдите расстояние между серединами отрезков ОА и ОВ, если точка О: а) лежит на отрезке AB; б) не лежит на отрезке AB.</text>
				</question>
				<question>
					<q_id>39</q_id>
					<text>Отрезок, длина которого равна а, разделен произвольной точкой на два отрезка. Найдите расстояние между серединами этих отрезков.</text>
				</question>
				<question>
					<q_id>40</q_id>
					<text>Отрезок, равный 28 см, разделен на три неравных отрезка. Расстояние между серединами крайних отрезков 16 см. Найдите длину среднего отрезка.</text>
				</question>
			</questions_block>
		</paragraph>
		<paragraph>
			<p_id>5</p_id>
			<p_name>Измерение углов</p_name>
			<section>
				<s_id>9</s_id>
				<s_name>Градусная мера угла</s_name>